### ISSUE TITLE
Json parse error when downloading dataset from hf

### ISSUE THREAD

**Issue by KaiLv69** [yuchenlin/LLM-Blender#3]
I tried to download dataset but got error like
``` bash
Generating train split: 75189 examples [08:46, 2716.79 examples/s]Failed to read file './hf_cache/downloads/c652d27b07a7ba1e26291b441d095
edd970a5045e4c1126d0d02e87e805d07e4' with error <class 'pyarrow.lib.ArrowInvalid'>: JSON parse error: Missing a closing quotation mark in
 string. in row 6                                                                                                                        
Traceback (most recent call last):                                 
  File "/remote-home/klv/src/rtv/lib/python3.8/site-packages/datasets/packaged_modules/json/json.py", line 134, in _generate_tables
    dataset = json.load(f)
  File "/remote-home/klv/src/rtv/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/remote-home/klv/src/rtv/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/remote-home/klv/src/rtv/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 12658)

During handling of the above exception, another exception occurred:

Traceback (most recent call last): 
  File "/remote-home/klv/src/rtv/lib/python3.8/site-packages/datasets/builder.py", line 1879, in _prepare_split_single
    for _, table in generator:
  File "/remote-home/klv/src/rtv/lib/python3.8/site-packages/datasets/packaged_modules/json/json.py", line 137, in _generate_tables
    raise e
  File "/remote-home/klv/src/rtv/lib/python3.8/site-packages/datasets/packaged_modules/json/json.py", line 113, in _generate_tables
    pa_table = paj.read_json(
  File "pyarrow/_json.pyx", line 259, in pyarrow._json.read_json
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: JSON parse error: Missing a closing quotation mark in string. in row 6

The above exception was the direct cause of the following exception: 


Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/remote-home/klv/src/rtv/lib/python3.8/site-packages/datasets/load.py", line 1797, in load_dataset
    builder_instance.download_and_prepare(
  File "/remote-home/klv/src/rtv/lib/python3.8/site-packages/datasets/builder.py", line 909, in download_and_prepare
    self._download_and_prepare(
  File "/remote-home/klv/src/rtv/lib/python3.8/site-packages/datasets/builder.py", line 1004, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "/remote-home/klv/src/rtv/lib/python3.8/site-packages/datasets/builder.py", line 1767, in _prepare_split
    for job_id, done, content in self._prepare_split_single(
  File "/remote-home/klv/src/rtv/lib/python3.8/site-packages/datasets/builder.py", line 1912, in _prepare_split_single
    raise DatasetGenerationError("An error occurred while generating the dataset") from e
datasets.builder.DatasetGenerationError: An error occurred while generating the dataset
```

**Comment by yuchenlin** [comment]
@jdf-prog  would u plz take a look at this issue? I remember we fixed a data loading bug before, not sure if this is the same one.

**Comment by jdf-prog** [comment]
@KaiLv69 Could you plz provide the original code for downloading? Because on my machine the downloading works fine with 
`from datasets import load_dataset

dataset = load_dataset("llm-blender/mix-instruct")`
and you can see the datasets info by `print(dataset)`

```
DatasetDict({
    train: Dataset({
        features: ['id', 'instruction', 'input', 'output', 'candidates', 'cmp_results'],
        num_rows: 100000
    })
    validation: Dataset({
        features: ['id', 'instruction', 'input', 'output', 'candidates', 'cmp_results'],
        num_rows: 5000
    })
    test: Dataset({
        features: ['id', 'instruction', 'input', 'output', 'candidates', 'cmp_results'],
        num_rows: 5000
    })
})
```

**Comment by KaiLv69** [comment]
Thanks for your reply. It seems like an issue with hf datasets' cache and I've fixed it.
